import { Link, useOutletContext } from 'react-router-dom'
import AdminNav from '../components/AdminNav'
import Icon from '../components/Icons'
import { formatPrice } from '../data/cars'

export default function AdminDashboard() {
  const { cars } = useOutletContext()
  const counts = { total: cars.length, available: cars.filter(car => car.status === 'AVAILABLE').length, reserved: cars.filter(car => car.status === 'RESERVED').length, sold: cars.filter(car => car.status === 'SOLD').length }
  return <div className="admin-page admin-page-inner"><div className="container"><AdminNav /><div className="admin-top"><div><p className="kicker">CARVENTORY / ADMIN</p><h1>Good morning, <em>Arjun.</em></h1></div><Link to="/" className="text-link">View storefront <Icon name="arrow" size={16} /></Link></div><div className="admin-stats"><Stat label="TOTAL CARS" value={counts.total} note="In your collection" /><Stat label="AVAILABLE" value={counts.available} note="Ready for a new road" /><Stat label="RESERVED" value={counts.reserved} note="Across your locations" /><Stat label="SOLD" value={counts.sold} note="This inventory cycle" /><Stat label="NEW ENQUIRIES" value="06" note="Need your attention" /></div><div className="container admin-content admin-content-dashboard"><div className="admin-panel"><div className="panel-heading"><div><p className="eyebrow">INVENTORY OVERVIEW</p><h2>Recent cars</h2></div><Link className="button button-primary" to="/admin/cars/new">Add a car <Icon name="arrow" size={16} /></Link></div><div className="admin-car-list">{cars.slice(0, 5).map(car => <div className="admin-car-row" key={car.id}><img src={car.image} alt="" /><div><strong>{car.brand} {car.model}</strong><span>{car.year} · {car.variant}</span></div><span className="admin-price">{formatPrice(car.price)}</span><span className={`status-tag ${car.status.toLowerCase()}`}>{car.status}</span><Link to={`/admin/cars/${car.id}/edit`} aria-label={`Edit ${car.model}`}>•••</Link></div>)}</div></div><aside className="admin-side-panel"><p className="eyebrow">QUICK ACTIONS</p><Link to="/admin/inventory"><Icon name="search" size={18} /> Manage inventory <span>↗</span></Link><Link to="/admin/enquiries"><Icon name="user" size={18} /> Review enquiries <span>06</span></Link><Link to="/admin/cars/new"><Icon name="bolt" size={18} /> Add a new car <span>↗</span></Link></aside></div></div></div>
}

function Stat({ label, value, note }) { return <div><span>{label}</span><strong>{value}</strong><small>{note}</small></div> }
