import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import CarCard from '../components/CarCard'
import Icon from '../components/Icons'
import useCarFilters from '../hooks/useCarFilters'
import { useCarsContext } from '../context/CarContext'

export default function Cars() {
  const [searchParams] = useSearchParams()
  const [view, setView] = useState('grid')
  const { loading, error } = useCarsContext()
  const { filters, updateFilter, clearFilters, sortBy, setSortBy, visibleCars, options, hasFilters } = useCarFilters()
  useEffect(() => { if (searchParams.get('search')) updateFilter('search', searchParams.get('search')) }, [searchParams])
  if (loading) return <div className="api-state container"><h1>Loading cars...</h1><p>Fetching latest inventory from database.</p></div>
  if (error) return <div className="api-state container"><h1>Unable to load cars. Please try again.</h1><p>{error}</p></div>
  return <div className="page-shell"><section className="page-hero container"><div><p className="kicker">THE COLLECTION</p><h1>Find your <em>next car.</em></h1><p>Browse our verified car inventory with full specifications and photos.</p></div><div className="inventory-count"><strong>{visibleCars.length}</strong><span>cars<br />available</span></div></section><section className="container inventory-layout"><aside className="filter-rail"><p className="eyebrow">REFINE BY</p><label className="filter-search"><Icon name="search" size={16} /><input value={filters.search} onChange={event => updateFilter('search', event.target.value)} placeholder="Search cars" /></label><FilterSelect label="Condition" name="condition" value={filters.condition} onChange={updateFilter} options={['ALL', 'NEW', 'USED']} /><FilterSelect label="Fuel type" name="fuel" value={filters.fuel} onChange={updateFilter} options={['ALL', ...options.fuels]} /><FilterSelect label="Transmission" name="transmission" value={filters.transmission} onChange={updateFilter} options={['ALL', 'Automatic', 'Manual']} /><FilterSelect label="Location" name="location" value={filters.location} onChange={updateFilter} options={['ALL', ...options.locations]} /><FilterSelect label="Year" name="year" value={filters.year} onChange={updateFilter} options={['ALL', ...options.years]} /><FilterSelect label="Max price" name="maxPrice" value={filters.maxPrice} onChange={updateFilter} options={[['ALL', 'Any price'], [1000000, '₹10 lakh'], [1500000, '₹15 lakh'], [2000000, '₹20 lakh'], [3000000, '₹30 lakh']]} />{hasFilters && <button className="clear-filters" onClick={clearFilters}>Clear all filters</button>}</aside><div className="inventory-results"><div className="results-toolbar"><span><strong>{visibleCars.length} cars</strong> found</span><div className="toolbar-actions"><button className={view === 'grid' ? 'selected' : ''} onClick={() => setView('grid')}>Grid</button><button className={view === 'list' ? 'selected' : ''} onClick={() => setView('list')}>List</button><select className="sort-button" value={sortBy} onChange={event => setSortBy(event.target.value)}><option value="recommended">Sort: Recommended</option><option value="priceAsc">Price: Low → High</option><option value="priceDesc">Price: High → Low</option><option value="yearDesc">Year: Newest</option><option value="yearAsc">Year: Oldest</option><option value="kmAsc">KM: Low → High</option></select></div></div>{visibleCars.length ? <div className={`car-grid ${view === 'list' ? 'list-view' : ''}`}>{visibleCars.map(car => <CarCard key={car.id} car={car} />)}</div> : <div className="no-results"><Icon name="search" size={26} /><h3>No cars found.</h3><p>Try clearing your filters or search terms.</p><button className="text-link" onClick={clearFilters}>Clear filters <Icon name="arrow" size={15} /></button></div>}</div></section></div>
}

function FilterSelect({ label, name, value, onChange, options }) {
  return <label className="filter-select"><span>{label}</span><select value={value} onChange={event => onChange(name, event.target.value)}>{options.map(option => { const [optionValue, optionLabel] = Array.isArray(option) ? option : [option, option === 'ALL' ? `All ${label.toLowerCase()}` : option]; return <option key={optionValue} value={optionValue}>{optionLabel}</option> })}</select></label>
}
