spring.application.name=carventory-backend
server.port=${SERVER_PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/carventory}

spring.jackson.serialization.write-dates-as-timestamps=false
